
services:

  mysql:
    image: mysql
    ports:
      - "3308:3306"
    volumes:
      - database:/var/lib/mysql
    container_name: app_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db

volumes:
  database:
